name: fitnesspal
description: "A holistic wellness tracking app combining habit tracking, nutrition analysis, activity logging, and AI insights."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  fl_chart: ^0.68.0
  intl: ^0.19.0
  smooth_page_indicator: ^1.1.0
  firebase_core: ^4.9.0
  cloud_firestore: ^6.4.1
  lucide_icons: ^0.257.0
  firebase_auth: ^6.5.1
  google_sign_in: ^7.2.0
  sign_in_with_apple: ^7.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  firebase_core_platform_interface: ^7.0.1

flutter:
  uses-material-design: true
