// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJ2Svxt7MpC_nVCiOG3bZ8ZXM5xi0k8MA',
    appId: '1:370106486674:web:1b0f54682e2e0c1f497b4b',
    messagingSenderId: '370106486674',
    projectId: 'fitnesspal-149a7',
    authDomain: 'fitnesspal-149a7.firebaseapp.com',
    storageBucket: 'fitnesspal-149a7.firebasestorage.app',
    measurementId: 'G-BGB35BH60N',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0YQD-FvicOZzzhT_7G7P79S1dA5RP7_o',
    appId: '1:370106486674:ios:b072d59b2faecafd497b4b',
    messagingSenderId: '370106486674',
    projectId: 'fitnesspal-149a7',
    storageBucket: 'fitnesspal-149a7.firebasestorage.app',
    iosBundleId: 'com.example.fitnesspal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC0YQD-FvicOZzzhT_7G7P79S1dA5RP7_o',
    appId: '1:370106486674:ios:b072d59b2faecafd497b4b',
    messagingSenderId: '370106486674',
    projectId: 'fitnesspal-149a7',
    storageBucket: 'fitnesspal-149a7.firebasestorage.app',
    iosBundleId: 'com.example.fitnesspal',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA761ppRkiHyKt1aBpoK3ZAxhgB3u-vRvI',
    appId: '1:370106486674:android:5fe12f2da12e252c497b4b',
    messagingSenderId: '370106486674',
    projectId: 'fitnesspal-149a7',
    storageBucket: 'fitnesspal-149a7.firebasestorage.app',
  );

}